services:
  ts-aiostreams:
    image: tailscale/tailscale:latest
    container_name: ts-aiostreams
    hostname: ts-aiostreams
    environment:
      - TS_AUTHKEY= your OAuth key from tailscal
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_SERVE_CONFIG=/config/serve-config.json
    volumes:
      - ./state:/var/lib/tailscale
      - ./config:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    ports:
      - 3000:3000
  aiostreams:
    image: ghcr.io/viren070/aiostreams:latest
    container_name: aiostreams
    network_mode: service:ts-aiostreams
    depends_on:
      - ts-aiostreams
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    healthcheck:
      test: wget -qO- http://localhost:3000/api/v1/status
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped
